### ISSUE TITLE
matplotlib unit testing

### ISSUE THREAD

**Issue by mlp6** [kmc97/ImageProcessorS18#30]
check out `matplotlib.testing.decorators.image_comparison`... it is the `bomb.com`

**Comment by kmc97** [comment]
wondering if i should be getting errors when simply importing matplotlib in the top of my testing file...

**Comment by mlp6** [comment]
Details?

**Comment by kmc97** [comment]
@mlp6 wellllll turns out i added this fun command matplotlib.use('Agg') to the top of my test file and it made things less angry (aka it got rid of the tkinter errors).  Its still failing travis-- but i think i know why and its more of a tomorrow problem
