### ISSUE TITLE
Histogram Equalization, Contrast Streching, Log compression, reverse Video

### ISSUE THREAD

**Issue by kmc97** [kmc97/ImageProcessorS18#8]
these MRI's of the UCL are pretty poor, need to enhance them before we can futher manipulate

**Comment by kmc97** [comment]
im looking at and basing my code off of http://scikit-image.org/docs/stable/auto_examples/color_exposure/plot_equalize.html#sphx-glr-auto-examples-color-exposure-plot-equalize-py 

Having some issues with:
1. executing adaptive equalization, this is the error:
![image](https://user-images.githubusercontent.com/32279493/39003911-ee8581ae-43c9-11e8-8021-99d3962b5fb6.png)

I see "KeyError: ((1,1,3), '<f8') and become immediately confused lol

2. histogram equalization results in a blue picture-- which i think i just need to convert to grayscale somehow so nbd

code is uploaded to kmc97/image_processing branch

**Comment by souhaila30** [comment]
in line 30, you defined apative_equalization and using img_hist as an input. Where is img_hist defined?Also, where is nump_array defined? Is that the array of the image?

**Comment by kmc97** [comment]
heygirl... working it out on a jupyter notebook... so far so good. ill let you know whats going on.

Basically to do  any image processing, we have to transform the picture into a numpy array.. so thats right we have to transform between picture and base64 AND picture and numpy array. this can be found in manipulate data.py

**Comment by kmc97** [comment]
just need to do log compress. going to close this issue to make more specific
